import os, sys
import numpy as np
from subprocess import Popen, PIPE
import subprocess, shlex
from time import gmtime, strftime
import math
import multiprocessing as mp
import argparse
import copy
from shutil import copyfile
from distutils.dir_util import copy_tree
import time
# from numba import njit, jit
from string import ascii_uppercase
from pathlib import Path
import re
import datetime
import random
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.colors as colors
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.font_manager import FontProperties
from matplotlib.patches import Rectangle
import matplotlib.patches as patches

##### 
# reads in 2 column file and adds 2nd column to pdb beta factor column

# Fonts

alignment = {'horizontalalignment': 'center', 'verticalalignment': 'baseline'}
families = ['serif', 'sans-serif', 'cursive', 'fantasy', 'monospace']
styles = ['normal', 'italic', 'oblique']
font = FontProperties()

#  tick fonts
font1 = font.copy()
font1.set_family('sans-serif')
font1.set_style('normal')

# label fonts
font2 = font.copy()
font2.set_family('sans-serif')
font2.set_style('normal')
font2.set_weight('normal')
plt.rcParams['mathtext.default'] = 'regular'
plt.rcParams['axes.linewidth'] = 6
bbox = dict(boxstyle="round", fc="0.8")
cmaps = [('Perceptually Uniform Sequential', [
            'viridis', 'plasma', 'inferno', 'magma']),
         ('Sequential', [
            'Greys', 'Purples', 'Blues', 'Greens', 'Oranges', 'Reds',
            'YlOrBr', 'YlOrRd', 'OrRd', 'PuRd', 'RdPu', 'BuPu',
            'GnBu', 'PuBu', 'YlGnBu', 'PuBuGn', 'BuGn', 'YlGn']),
         ('Sequential (2)', [
            'binary', 'gist_yarg', 'gist_gray', 'gray', 'bone', 'pink',
            'spring', 'summer', 'autumn', 'winter', 'cool', 'Wistia',
            'hot', 'afmhot', 'gist_heat', 'copper']),
         ('Diverging', [
            'PiYG', 'PRGn', 'BrBG', 'PuOr', 'RdGy', 'RdBu',
            'RdYlBu', 'RdYlGn', 'Spectral', 'coolwarm', 'bwr', 'seismic']),
         ('Qualitative', [
            'Pastel1', 'Pastel2', 'Paired', 'Accent',
            'Dark2', 'Set1', 'Set2', 'Set3',
            'tab10', 'tab20', 'tab20b', 'tab20c']),
         ('Miscellaneous', [
            'flag', 'prism', 'ocean', 'gist_earth', 'terrain', 'gist_stern',
            'gnuplot', 'gnuplot2', 'CMRmap', 'cubehelix', 'brg', 'hsv',
            'gist_rainbow', 'rainbow', 'jet', 'nipy_spectral', 'gist_ncar'])]


def pdbatom(line):
### get information from pdb file
### atom number, atom name, residue name,chain, resid,  x, y, z, backbone (for fragment), connect(for fragment)
    try:
        return dict([('atom_number',str(line[7:11]).replace(" ", "")),('atom_name',str(line[12:16]).replace(" ", "")),('residue_name',str(line[17:21]).replace(" ", "")),('chain',line[21]),('residue_id',int(line[22:26])), ('x',float(line[30:38])),('y',float(line[38:46])),('z',float(line[46:54])), ('backbone',int(float(line[56:60]))),('connect',int(float(line[60:67])))])
    except:
        sys.exit('\npdb line is wrong:\t'+line) 

def create_pdb(file_name):
    pdb_output = open(file_name, 'w')
    # pdb_output.write('REMARK    GENERATED BY sys_setup_script\nTITLE     SELF-ASSEMBLY-MAYBE\nREMARK    Good luck\n\
# '+box_vec+'MODEL        1\n')
    return pdb_output

rmsf = []
with open('col1.xvg', 'r') as xvg_input:
    for line_nr, line in enumerate(xvg_input.readlines()):
    	if len(line) > 0:
    		rmsf.append(float(line)*10)

# pdbline = "ATOM  %5d %4s %4s%1s%4d    %8.3f%8.3f%8.3f%6.2f%6.2f"

# pdb_output =create_pdb('udp2_rmsf.pdb')
# with open('udp.pdb', 'r') as pdb_input:
#     resid_prev = -1
#     for line_nr, line in enumerate(pdb_input.readlines()):
#         if line.startswith('ATOM'):
#             line_sep = pdbatom(line)
#             # print(line_sep)
#             pdb_output.write(pdbline%((int(line_sep['atom_number']),line_sep['atom_name'],line_sep['residue_name'],' ',line_sep['residue_id'],\
# 							line_sep['x'],line_sep['y'],line_sep['z'],1,rmsf[line_nr]))+'\n')


plt.figure(1, figsize=(20,15))
plt.title('WaaL apo',  fontproperties=font1, fontsize=30,y=1.1)
plt.subplot(3,1,1)
plt.plot(np.arange(1, len(rmsf)+1,1),rmsf,  color='black',linewidth=3, label='repeat 1')
# plt.axvline(1,ymin=-10, ymax=210, linewidth=4,color='k') # LHBU
# plt.axvline(6,ymin=-10, ymax=210, linewidth=4,color='k') # LHBU


plt.xticks(np.arange(0, 180,20), fontproperties=font1,  fontsize=30)
plt.yticks(np.arange(0, 1000,2), fontproperties=font1,  fontsize=30)#
plt.ylim(2,10)
plt.xlim(-1, 165)

plt.xlabel('Atom Number', fontproperties=font2,fontsize=30) 
plt.ylabel('RMSF (nm)', fontproperties=font2,fontsize=30) 
plt.subplots_adjust( top=0.9, bottom=0.12, left=0.1,right=0.991, wspace=0.3, hspace=0.3)

plt.savefig('UDP2_rmsf.png', dpi=300)
plt.show()